[build]
  command = "npm run build"
  publish = "public/"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@arcgis/core"]

[dev]
  framework = "remix"
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

# Cypress plugin
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    # run E2E tests against the deployed URL
    record = true
    group = 'deployed'
